[project]
name = "pyinstxtractor-ng"
version = "2026.07.03"
description = "PyInstaller Extractor Next Generation"
authors = [{ name = "extremecoders-re" }]
license = "GPL-3.0-only"
readme = "README.md"
packages = [{ include = "pyinstxtractor_ng.py" }]
dependencies = ["xdis==6.3.0", "pycryptodome==3.17"]
requires-python = ">=3.8"

[project.scripts]
pyinstxtractor-ng = 'pyinstxtractor_ng:main'

[tool.poetry.dependencies]
python = ">=3.8,<3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

xdis = { git = "https://github.com/rocky/python-xdis", rev="3372ebaf776c7f0a99c126678420bc7bf8d027ef"}

